version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: sistema-devedores-db
    restart: always
    environment:
      POSTGRES_DB: sistema_devedores
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devedores-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sistema-devedores-pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@devedores.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - devedores-network

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SESSION_PHONE_CLIENT=SistemaDevedores
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=sua_chave_aqui_123
      - SERVER_URL=http://localhost:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - devedores-network

volumes:
  postgres_data:
  pgadmin_data:
  evolution_instances:
  evolution_store:

networks:
  devedores-network:
    driver: bridge
