// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcpbwgmikemhaplpgsww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcGJ3Z21pa2VtaGFwbHBnc3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDgyNzgsImV4cCI6MjA2MzU4NDI3OH0.26r3KUrarDQY72oHDfNDFhH6-c8t4Z88Cjibq0C-u0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);